ReactiveCocoa/ReactiveSwift

ReactiveSwift/Deprecations+Removals.swift

Thanks for migration support 👍

Fix typo in TestScheduler renames

---

Sources/Disposable.swift
Tests/ReactiveSwiftTests/DisposableSpec.swift

[ScopedDisposable] Fix infinite loop in `init(_ disposable: Disposable)`

---

Cartfile.private
Cartfile.resolved

Update Quick to v0.10.0

---

.travis.yml
ReactiveSwift.podspec
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-macOS.xcscheme
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-watchOS.xcscheme

I will push the podspec to CocoaPods Trunk once this is merged.

Update podspec for pushing 1.0.0-alpha.1 to trunk

---

.travis.yml
Package.swift
Sources/Scheduler.swift
Tests/LinuxMain.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

A follow up to #43. This depends on the changes in https://github.com/Quick/Nimble/pull/342.

Run the test suites on Linux

---

Sources/Deprecations+Removals.swift

Fixed the signatures of four deprecated free functions.

---

.travis.yml

Should fix the test failure of https://github.com/ReactiveCocoa/ReactiveSwift/pull/80#issuecomment-258507521.

[SwiftPM] Update Nimble

---

.Package.test.swift
.travis.yml
Cartfile.private
Cartfile.resolved

https://github.com/Quick/Quick/releases/tag/v1.0.0

Update Quick to v1.0.0

---

.travis.yml

https://blog.travis-ci.com/2016-12-13-xcode-82-ga-is-here

[Travis] Use Xcode 8.2 image

---

script/gen-docs

Fixed the symlink generation in the gen-docs script.

---

Sources/Signal.swift

A simpler implementation of `debounce`.
Note: The current implementation depends on a likely fraudulent behaviour of `SignalProducer` (#227) to work correctly, and would break if the fraudulent behaviour is fixed.

New `debounce` implementation.

---

README.md

Missing `signal` from `currentTime: Property<TimeInterval>` before `observe`.

Correct example with Property and Signal

---

.Package.test.swift
.travis.yml
Cartfile.private
Cartfile.resolved

Quick now supports SwiftPM on macOS!
https://github.com/Quick/Quick/pull/687

[Travis] Run `swift test` on macOS

---

.Package.test.swift
.travis.yml
Cartfile.private
Cartfile.resolved

https://github.com/Quick/Quick/releases/tag/v1.1.0

Update Quick to v1.1.0

---

Documentation/FrameworkOverview.md
README.md

Update `Lifetime.makeLifetime` in docs to its new name.

---

Sources/Signal.swift
Sources/SignalProducer.swift

This came up in Slack today. I think this makes it a little clearer.

Try to clarify throttle/debounce

---

Sources/Action.swift
Sources/Atomic.swift

Deprecate ActionProtocol.

---

.travis.yml
Cartfile.private
Cartfile.resolved

See https://github.com/Quick/Nimble/pull/397 for the details.

Update Nimble to be built with Swift 3.1

---

.travis.yml

this should (hopefully) fix Travis WatchOS build failing

fix watch ci

---

README.md

Mention the UI examples playground in README.

---

ReactiveSwift.playground/Pages/Property.xcplaygroundpage/Contents.swift

Fixing a typo in playground.
It's not urgent. please review in your free time :)

fix small typo in playground

---

.jazzy.yaml

Update Jazzy configuration.

---

Sources/Flatten.swift

Avoid the active signal from being retained in the race strategy.

---

Sources/Lifetime.swift

[Lifetime] Use Never for `ended` signal

---

.travis.yml

https://blog.travis-ci.com/2017-05-11-introducing-build-stages

[Travis] Try Build Stages beta feature

---

README.md

I do wish to mention reactive collections, but it seems not everyone is interested in it for now. 😕

Update the release roadmap. [skip ci]

---

Sources/Signal.swift

1. Update implementation docs.
2. Rename `shellDidDeinitialize` to `signalDidDeinitialize`.
-  ~~Updated CHANGELOG.md.~~

[Gardening] Signal.Core.

---

CHANGELOG.md

Update the change log for 2.0.0 alpha 1. [skip ci]

---

CHANGELOG.md

Changelog for producer operator lifting improvements.

---

Cartfile.private
Cartfile.resolved
Package.pins
Package.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

https://github.com/Quick/Nimble/releases/tag/v7.0.1

Update Nimble to 7.0.1 for Xcode 9 compatibility

---

README.md

Update the release roadmap for latest Swift 4 progress.

---

Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

Mitigate random failures in the MutableProperty async deadlock test and Action infinite feedback test.

---

.travis.yml
Package.resolved
Package.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

- Log the Swift version
- Test Swift 4 builds

Expanded CI builds

---

Sources/Scheduler.swift

Change of an Implementation detail.
- ~Updated CHANGELOG.md.~

No cancel token if the action is immediately consumed by UIScheduler.

---

script/gen-docs

Fix relative links in the generated documentation. [skip ci]

---

script/gen-docs

Force `cp` to overwrite the Dash feed file. [skip ci]

---

Sources/UnidirectionalBinding.swift

This is a change in the implementation detail. The two static overloads are folded into their async counterparts as a runtime fast path for `ImmediateScheduler`. This reduces the number of overloads as we extend BindingTarget in RAC.

Replace two BindingTarget.init overloads with ImmediateScheduler.

---

Documentation/FrameworkOverview.md

Fix link to Design Guidelines in the documentation

---

Sources/Flatten.swift

FlattenStrategy is used by signals and properties too. So it might be better to use wordings like _stream of streams_, _inner streams_ and _the flattened stream of values_. It also clarifies how `interrupted` and `failure` from inner streams would behave.

Update the flatten strategy descriptions. [skip ci]

---

ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Contents.swift
ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Sources/UIKitExtensions.swift

Updated the playground for 2.0 RC1, and added the notes on how to make the playground run.

Update the ValidatingProperty playground.

---

Sources/Property.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

MutableProperty can be right operand in logical operations

---

ReactiveSwift.playground/Pages/Property.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Signal.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift

Hi ReactiveSwift team!
I found several links that is not working in ReactiveSwift.playground. This pull request fixes those links. Please take a look at it.
Should I update CHANGELOG.md even when a PR is just a documentation fix? If so, please let me know, then I will update CHANGELOG.md. Thanks!

Fix links in ReactiveSwift.playground

---

.travis.yml
script/build

_(Playground is disabled for Xcode 9 builds until tuple destructuring is back.)_

Add Xcode 9 CI tests.

---

CHANGELOG.md
Sources/Deprecations+Removals.swift
Sources/Lifetime.swift
Sources/Property.swift
Sources/SignalProducer.swift

Resurrect `+=` for adding disposables to lifetime.

---

Sources/Signal.swift

Fixes #490.
-  ~~Updated CHANGELOG.md.~~

SwiftPM 4.0 build fix

---

README.md

Mention ReactiveCollections. [skip ci]

---

Documentation/RxComparison.md

correct links to FrameworkOverview.md

---

.travis.yml

[CI] Cache Carthage's cache directory

---

Sources/Disposable.swift

[gardening] Use _SimpleDisposable in AnyDisposable

---

CHANGELOG.md
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-iOS.xcscheme
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-tvOS.xcscheme

See https://github.com/Carthage/Carthage/issues/2056.

iOS + tvOS: disable code coverage to fix app submission with Xcode 9

---

ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-macOS.xcscheme

Disable code coverage for the macOS target.

---

ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Sources/FormView.swift

As suggested in https://github.com/ReactiveCocoa/ReactiveSwift/issues/403.

Add a missing import in a UI playground source.

---

Sources/Action.swift
Sources/Property.swift

[gardening] Utilize `Lifetime.make()`

---

.travis.yml

As a reaction to https://blog.travis-ci.com/2017-09-22-macos-update.

[CI] Unify Carthage jobs into one to reduce macOS jobs

---

.travis.yml

Use Swift 4.0 for SwiftPM builds.

---

Sources/Bag.swift
Sources/Signal.swift

[gardening] Use `Sequence.indices` over forming a range

---

Tests/ReactiveSwiftTests/SignalProducerNimbleMatchers.swift

[gardening] Use the new `Predicate` type for Nimble matchers

---

.travis.yml
script/build

As a reaction to https://blog.travis-ci.com/2017-09-22-macos-update.
See also #528.

[CI] Unify xcodebuild jobs to reduce macOS jobs

---

Cartfile.private
Cartfile.resolved
Package.pins
Package.swift

Update Quick and Nimble

---

Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Add a producer interruption test case.

---

Sources/FoundationExtensions.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

[gardening] Remove unnecessary conditional code

---

Documentation/APIContracts.md
Sources/SignalProducer.swift

Update the documentation.

---

CHANGELOG.md
Sources/Flatten.swift
Sources/SignalProducer.swift

Fix some documentation errors

---

Sources/Action.swift
Sources/Flatten.swift
Sources/Property.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

[gardening] Use `Lifetime.+=` where possible

---

Tests/ReactiveSwiftTests/PropertySpec.swift

Refactor the MutableProperty deadlock test randomly failing on Linux.

---

Tests/ReactiveSwiftTests/SignalProducerNimbleMatchers.swift

I wrote some code based off this custom Nimble matcher, but then since my team treats warnings as errors it wouldn't compile because `NonNilMatcherFunc` is deprecated. 😅  
Wanted to contribute our fixes back!
Tested this by writing various failing tests in `SignalProducerSpec`, none of which should actually be committed. 😄 
☝️ I didn't do this because it's just a change in the test code but am happy to add an entry too if desired.

Fix deprecation in SignalProducerNimbleMatchers

---

Sources/Scheduler.swift

Added comment to DispatchSourceTimerWrapper.Equatable

---

Sources/Disposable.swift

[Gardening] Disposable

---

CHANGELOG.md
Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

This PR adds a new option to `debounce` to allow sending values upon completion.

Add `discardWhenCompleted` to `debounce`

---

Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Rewrite names of a few test case. Disable four test cases.

---

.travis.yml

[CI] Test with swift-4.2-DEVELOPMENT-SNAPSHOT on Linux

---

.travis.yml
CHANGELOG.md
ReactiveSwift.podspec

[podspec] Add cocoapods_version and swift_version to be explicit

---

CHANGELOG.md
ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Sandbox.xcplaygroundpage/Contents.swift

[Documentation Improvement] No longer pass --no-use-binaries option

---

ReactiveSwift.playground/Pages/Signal.xcplaygroundpage/Contents.swift

remove unneeded `? true : false`

---

.travis.yml
Cartfile.private
Cartfile.resolved

[CI] Test with Xcode 10 beta

---

.travis.yml
Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift
Package@swift-4.2.swift
script/build

[CI] Test Swift 4.2

---

CHANGELOG.md
Sources/Event.swift
Sources/Scheduler.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift

I fixed legacy date implementation.

Fix legacy date implementation

---

Sources/Atomic.swift

Added an overlooked missing comments slash.

Updated docs formatting

---

Documentation/RxComparison.md

There is a typo in the link, this commit fixes it

Fix broken link

---

Cartfile
Cartfile.resolved
Package.resolved
Package.swift
Package@swift-4.2.swift
ReactiveSwift.podspec
Sources/ResultExtensions.swift

https://github.com/antitypical/Result/releases/tag/4.1.0
~~- [ ] Updated CHANGELOG.md.~~

Update Result to 4.1.0

---

Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift
Package@swift-4.2.swift

Update Nimble to 7.3.2

---

.travis.yml
Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift
Package@swift-4.2.swift

Test Swift 5.0 compiler (5.0-DEVELOPMENT-SNAPSHOT-2019-01-27-a) on Linux

---

Documentation/Example.OnlineSearch.md

This commit fixes broken links.

Fix broken links

---

ReactiveSwift.podspec

I missed this in https://github.com/ReactiveCocoa/ReactiveSwift/pull/712.

[podspec] Update `swift_version` to 4.2

---

Sources/Event.swift
Sources/Signal.swift

This fixes compilation on `Xcode 11` / `Swift 5.1`.

Signal: using Signal.Event.promoteValue

---

CHANGELOG.md
ReactiveSwift.podspec
Sources/Info.plist
Tests/ReactiveSwiftTests/Info.plist

Bump version to 6.1.0

---

CHANGELOG.md
Package.swift

https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#supportedplatform

[SwiftPM] Add platforms

---

.github/workflows/master.yml

Remove .swift-version when verifying podspec

---

README.md

Didn't update CHANGELOG.md as AFAIK that's not required for a README change.

Add reactiveswift-composable-architecture to Extended Modules

---

.gitignore
Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift
Tests/ReactiveSwiftTests/SignalProducerNimbleMatchers.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Update to Nimble 9.0 and Quick 3.0

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Event.swift
Sources/Observers/SkipFirst.swift
Sources/Observers/SkipWhile.swift
Sources/Observers/TakeFirst.swift
Sources/Observers/TakeLast.swift
Sources/Observers/TakeWhile.swift

The new abstraction was introduced in #799.
Migrated operators in this PR include:
TakeFirst, TakeLast, TakeWhile, SkipFirst, SkipWhile 

Migrate five operators to the new abstraction.

---

.github/workflows/master.yml
ReactiveSwift.podspec
script/carthage

Update the Podspec and fix CI issues with Carthage verification.

---

CHANGELOG.md
Cartfile.private
Cartfile.resolved
ReactiveSwift.xcodeproj/project.pbxproj

Update Carthage xcconfig to 1.1

---

.gitmodules
Cartfile.private
Cartfile.resolved
ReactiveSwift.xcodeproj/project.pbxproj

This is a clean up PR for #826.

Use official xcconfigs repository

---

CHANGELOG.md
ReactiveSwift.podspec

Missed in #865
https://github.com/ReactiveCocoa/ReactiveSwift/pull/866#issuecomment-1373788659

Change Podfile iOS deployment minimum

---

Sources/Scheduler.swift

Updating the docs - to use the [distantFuture property](https://developer.apple.com/documentation/foundation/date/1779684-distantfuture)

Use Date property

---

CHANGELOG.md
ReactiveSwift.xcodeproj/project.pbxproj
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-xrOS.xcscheme
Sources/Property.swift

Add support for `xrOS`
