Sources/Flatten.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Recursively starting the inner producers can blow the stack if they
complete immediately.
Reopened from https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3161.

Rewrite concat to start producers iteratively

---

README.md

Fix broken link of `How does ReactiveSwift relate to Rx`

---

ReactiveSwift.playground/Pages/Signal.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift
Sources/Action.swift
Sources/Deprecations+Removals.swift
Sources/Event.swift
Sources/EventLogger.swift
Sources/Flatten.swift
Sources/FoundationExtensions.swift
Sources/Observer.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerNimbleMatchers.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

As discussed in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3013
I rather like this. I don’t think `next` is a particularly great name. `value` seems much better to me.
`Observer.sendValue()` becomes `Observer.send(value: )`
`Observer.sendFailed()` becomes `Observer.send(error: )`
`SignalProducer.startWithNext` becomes `SignalProducer.startWithValues`
`SignalProducer.observeNext` becomes `SignalProducer.startWithValues`

Rename `next` to `value`

---

.travis.yml
ReactiveSwift.podspec

After this is done, someone who wants to help maintain the podspec (I can do this, @nikita-leonov may be interested too). Someone will need to `pod trunk push ReactiveSwift.podspec --allow-warnings` (allowing warnings because there is not yet a tag on the repo, which CocoaPods prefers).
Let me know if there are any questions. 
Fixes #13.

Adds podspec

---

Sources/Disposable.swift

As implied by the documentation comment (and correctly so, IMO), it seems like the return value of this `Disposable.add` function overload should be discardable.

Add the @discardableResult attribute to a Disposable.add overload

---

.travis.yml
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Nanos conversion overflows on 32 bit devices because new dispatch API takes an Int and not Int64.
When interval and leeway get high enough and then we cast to Int, it overflows.

32bit arch crash: timer producer fails when interval is >= 3 seconds

---

Sources/Scheduler.swift

When modernizing the QueueScheduler API, I inadvertently left out the rare-but-useful case where work could be targeted to a specific destination queue.
This was driven by some late-breaking discussion in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2295.
This change is rather minimal in that it pushes the target queue into an optional parameter with a default nil value, so callers should not be forced to change.
I also intended for the API to be clear about the fact that we are targeting an existing queue, so callers (hopefully) won't end up "falling back" into the old pattern of targeting a global queue of their preferred priority.

Allow targeting work on a specific queue

---

Documentation/FrameworkOverview.md

None of the links that referenced types in the Documentation worked anymore, so I updated them to the current version.

Make links work again

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Property.swift
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

For representing write-only binding targets. Renamed `BindingTarget` the protocol to `BindingTargetProtocol`.
As suggested by @mdiep, a special variant `BindingTarget(setter:lifetime:on:)` is also included. It always synchronously triggers the setter action on the specified queue, or elides the dispatch if it is already on the same queue.
It should not cause any issues with the async operators, but only interoperating with explicit but perhaps strange uses of dispatch queues. e.g.
```
mainQueue.sync { anotherQueue.sync { mainQueueTarget <~ myProperty } }
```

Introduce `BindingTarget` (class).

---

Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

When making progress for the Rex PR, I hit a ~~weird~~ case which:
1. `Thread.isMainThread` is true;
2. `DispatchQueue.main.getSpecific(key: specificKey)` gives me the right queue id (for the main queue);
3. BUT `DispatchQueue.getSpecific(key: specificKey)` gives `nil`.
~~It seems it might be because of this:~~
> ~~https://developer.apple.com/reference/dispatch/1453125-dispatch_get_specific~~
>
> ~~This function is intended to be called from a block executing in a dispatch queue. You use it to obtain context data associated with the queue. Calling this method from code not running in a dispatch queue returns NULL because there is no queue to provide context.~~
The issue is in fact caused by the implicit nesting of `DispatchQueue.sync`. Somewhere in the middle of the call stack was a …

Use Schedulers in `BindingTarget`.

---

Sources/FoundationExtensions.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift

`Signal` starts right away, so the weak capturing of `observer` was removed.

`notifications` as Signal.

---

Sources/Flatten.swift
Sources/Property.swift
Sources/SignalProducer.swift

I've noticed this pattern being used in many places (also used in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3210), so this finally simplifies it.
Note the docstring explaining why we don't want to actually expose this, it's very important as it most certainly would be misused.

Created internal SignalProducer.startAndRetrieveSignal to simplify some implementations

---

Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

The new overloads flatten `Signal[Producer]<P, Error> where P: PropertyProtocol` into `Signal[Producer]<P.Value, Error>`.

`flatten` and `flatMap` overloads for `PropertyProtocol`.

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Reactive.swift
Tests/ReactiveSwiftTests/ReactiveExtensionsSpec.swift

It's useful to be able to attach reactive extensions to types, not just instances. This adds support for static members in Reactive extensions, adding a static `reactive` property to types conforming to `ReactiveExtensionsProvider`.

Allow reactive extensions to provide static members

---

ReactiveSwift.playground/Pages/Sandbox.xcplaygroundpage/Contents.swift

Added `--no-use-binaries` flag to playground setup through Carthage documentation as without it Carthage installs Result binary instead of checking out the sources. In such case Result build scheme is not defined and cannot be built.

Added `--no-use-binaries` flag 

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Fixes #77.
```
return SignalProducer { observer, compositeDisposable in
// ...
self.startWithSignal { signal, disposable in
compositeDisposable += disposable
compositeDisposable += signal.on(...).observe(observer)
```
The outer input observer was detached by the outer interruption, and this causes the started signal to dispose of itself (no observer + unreachable) under the new lifetime semantics. 
Moreover, since `CompositeDisposable` disposes its inner disposables in the reversed insertion order, the inner producer is interrupted after the said detachment and self-disposal happened.
So in the end, both together caused the injected side effect via `on` capturing no interrupted event. 
Generally speaking, the disposable of the outer observer to the produced inner signal should not be …

Fixed a bug in `on` which caused the signal to be disposed of too early.

---

.Package.test.swift
.travis.yml

We still run `swift test` on CI using separated `.Package.test.swift`.
This is the same as https://github.com/Carthage/Commandant/pull/83.

[SwiftPM] Remove test dependencies from `Package.swift`

---

Sources/Action.swift
Sources/Event.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

Adds a simple way to check if an event is a completed event, and to observe whenever an Action successfully completes.
One place I've used this is in error handling:
- Observe Action.errors and map over it to generate an error message for the UI.
- Observe Action.completed to clear the error message (it's useful to keep it around to provide the user context).

Add Event.isCompleted and Action.completed

---

Documentation/FrameworkOverview.md

As the title says.
Most is about the renaming of the events (`Next` -> `value`, lowercases) and the use of the Protocols rather than the types. Furthermore, `SignalProducer.buffer` is now gone.
Similar to the part about `DynamicProperty` which was deleted in #101 because its now in ReactiveCocoa, I've also deleted the part about `CocoaAction`.

Update Framework Overview for RAC 5.0

---

Sources/EventLogger.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Conceptually, `value` should be defined before `failed` since that goes in line with the natural order of events, however [this reordering](https://github.com/ReactiveCocoa/ReactiveCocoa/commit/85e2359d931c978b751940e066bcd95f0b215dd6) can introduce some confusion/inconvenience while using trailing closures specially during the migration from ReactiveCocoa 4.x where `value`, formerly known as `next`, was the last parameter and now represents `disposed`.
This can silently introduce some problems after migration if a project is using `.on` with a trailing closure to inject side-effects on values without being interested in the value itself.
```swift
producer.on { _ in 
// Inject side-effect, e.g. invalidate context
}
```
If we do not go forward with this we need to fix an inconsistency …

SignalProducer.on: restore `value` as the last parameter

---

ReactiveSwift.playground/Pages/Property.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Sandbox.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Signal.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift

Noticed this when reviewing #75.
This was removed in commit 923f07b1cd19bbf632f9fc9a9f078958168efe88.  It's referenced in the playground setup documentation and is useful, so restoring it.

Remove references to 'script/bootstrap' from playground documentation

---

Sources/Action.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

**Update:** Closes #88.
---
`PropertyAction` encapsulates the pattern where an `Action` should be enabled only if its input is non-nil.
The prime example of this pattern is form validation: validate some input text, and store the validated results in a property. If the form is valid, the property will be non-nil, and it should be safe to grab the current value and submit the form.
I've personally written a bunch of `Action`-based code that basically just implemented this logic in an ad-hoc fashion, so I think it would be super useful to have a convenient shorthand for it.
---
Ideally this could just be a convenience initialiser on `Action`:
```
extension Action where Input == Void {
// ...
}
```
But unfortunately this triggers Swift's "same-type requirement makes generic parameter …

Add initialisers to create an Action from an input property

---

Sources/Bag.swift

[Test Case 1 & 2](https://gist.github.com/andersio/5cc8fd27a8adccf70d53036505069db3#file-perftests-swift)
Same environment as in #124
One Observer:    0.018 sec (10%)
Eight Observers: 0.053 sec (5%)
One Observer:    0.012 sec (10%)
Eight Observers: 0.030 sec (6%)
One Observer:    0.010 sec (12%)
Eight Observers: 0.020 sec (3%)
Apparently no effect on iteration performance.

Optimize `Bag`.

---

Tests/ReactiveSwiftTests/SignalSpec.swift

Included in #123.
Note that the test case _"should interrupt concurrently"_ may not fail on Travis CI due to the limited concurrency. Running the test case locally should yield the expected result.

Failing test cases for race conditions in signal interruption (#123).

---

Documentation/DebuggingTechniques.md

* Name changes due to Swift 3.0 / ReactiveSwift 1.0
* Compiler Error has changed (I was just looking if that still confuses the compiler as of Xcode 8.1, and it still does)
* Removed `DynamicProperty` since its now in ReactiveCocoa
* Changed example with `UILabel.rac_text` to use a `MutableProperty<String>` instead.
* Fixed a broken link

Update DebuggingTechniques for ReactiveSwift 1.0

---

Documentation/DesignGuidelines.md

Its mostly the changes of event cases `Next` -> `value` and lowercasing. 
Since the `start(failed:completed:interrupted:next:)` and `observe(failed:completed:interrupted:next:)` overloads [have been removed](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/CHANGELOG.md#replacements-for-the-start-and-observer-overloads), maybe the whole *Switch over `Event` values* section can be removed, since thats now more or less the only way to do it anyway?

Update DesignGuidelines document

---

ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/contents.xcplayground
Sources/Deprecations+Removals.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Rename `times` to `repeat`.

---

Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

One less layer of wrapping = more joules saved.
If the signal created & passed to the `setUp` closure is neither retained nor observed, the producer disposable would be disposed of.
Detailed Example: https://github.com/ReactiveCocoa/ReactiveSwift/pull/106#issuecomment-263079737
Due to the new signal lifetime semantics in 1.0, the signal would have been disposed of upon exiting the scope of the closure. But the producer disposable does not follow the disposal of the produced signal - it is only disposed of until the upstream sends a termination event, or the producer is interrupted by the user.
In other words, it doesn't match the expected behaviour of `SignalProducer` having downstream disposals propagated back to the upstream.
This fix should IMO hardly affect any existing use case …

Refactored & Bugfix: `startWithSignal` and the hot-to-cold `lift`.

---

Sources/Deprecations+Removals.swift
Sources/Property.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

The PR proposes to have composed properties *not* retaining its sources. [This test case](https://github.com/ReactiveCocoa/ReactiveSwift/pull/117/files#diff-8719ae7a50d7fc426e03c8da6c209061R411) helps illustrate the new behaviour.
Recall that retaining `Property` would defer the termination of the event stream. Source capturing retains the sources, causing the sources' lifetime being a union with the lifetime of all their derivatives.
However, if we consider properties are just streams of values with a stronger guarantee than `Signal`s (having one latest value), operators - that are fundamentally an observation - should not have a side effect on the observed event stream. In this sense, source capturing should be dropped.
~~It also adds a new initializer `Property(reflecting:)`, which …

Remove Property source capturing.

---

Documentation/BasicOperators.md

All the examples have been update so that they work again (e.g. in the Playground)
Most changes were straightforward, like the renaming of methods and events.
However, the `.flatten` examples are a bit more complicated. Formerly, they relied on `SignalProducer.buffer` [which has been removed](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/CHANGELOG.md#signalproducer-buffer-has-been-removed). 
At first I wanted to preserve the same example behavior, first try was to use `MutableProperty` instead, but the examples need `completion` of the producer.
Next try was to use `SignalProducer.init(signal:).replyLazily(upto:)` but then it was necessary to additionally start these producers prior to the actual example (to achieve the same behavior as before).
Finally, I've simplified the …

Update Basic Operators for ReactiveSwift 1.0

---

Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

There are times where you'd like to throttle values whenever some condition is met, rather than based on a time interval.
This is inspired by ReactiveViewModel's `-throttleSignalWhileInactive:`.
Basic usage might involve a simple `MutableProperty` to toggle throttled values:
``` swift
let isActive = MutableProperty(false)
label.reactive.text <~ somethingChanged
.throttle(while: isActive.map(!), on: QueueScheduler())
.flatMap(.latest, transform: doSomethingExpensive)
.observeOn(UIScheduler())
// later
isActive.value = true
```
At some point it would be great to be able to throttle events while the view has disappeared:
``` swift
somethingChanged
.throttle(while: reactive.viewHasDisappeared, on: UIScheduler())
.startWithValues {
// expensive layout stuff
}
```
I'd love some feedback on …

Add throttle(while:on:)

---

Sources/Atomic.swift
Sources/Disposable.swift

`Disposable` is crucial part of the signal resource management, especially in transformed signals and `SignalProducer`s.
Previous attempt: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2463
~~This PR focuses on just `Disposable`. All disposables have a `DisposableState`, which exposes accessors built on top of OSAtomic primitives. `DisposableState` is made a `struct` so that the state is embedded into the containing class without extra indirection.~~
This PR introduces a lock-free primitive `UnsafeAtomicState`, and refactored all disposable types to use it. Note that the primitive is marked with `Unsafe` as it requires manual memory management.
Note that while `CompositeDisposable` and `SerialDisposable` still use `Atomic` for storing their children, they may still benefit from the …

Lock-free disposal.

---

Sources/Property.swift
Sources/Signal.swift
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

The idea here is to eliminate redundancy in things like https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3289.
By adding a `BindingSourceProtocol` type, both ends of `<~` become generic. That makes it easier to add conformance on either end.
This could also be called `Observable`—if we want to make it some more generic.
I'm curious what people think of this approach.

BindingSourceProtocol

---

.Package.test.swift
Cartfile
Cartfile.resolved
Package.swift
ReactiveSwift.podspec
Sources/Deprecations+Removals.swift
Sources/FoundationExtensions.swift

https://github.com/antitypical/Result/pull/198

Use AnyError for `URLSession.reactive.data(with:)`

---

Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

This PR is RAC port of `Rx.withLatestFrom` (namely, `sample(from:)`) with `samplee`'s error type constrained to `NoError` only.
Diagram: http://rxmarbles.com/#withLatestFrom
This was originally discussed in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2082 (not accepted), but I found this operator very useful because it is easy to fetch current state (`MutableProperty`) via `sourceSignal`:
```swift
let state: MutableProperty<String> = ...
sourceSignal
.sample(from: state.producer)
.observeValues { sourceValue, currentState in ... }
```
Above code is much easier to read compared to:
```swift
sourceSignal
.map { [unowned state] sourceValue in (sourceValue, state.value) }
.observeValues { sourceValue, currentState in ... }
```
or:
```swift
state.producer
.sample(with: sourceSignal) …
```

Add withLatest(from:) (Rx.withLatestFrom)

---

ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift
Sources/Deprecations+Removals.swift
Sources/Flatten.swift
Sources/Property.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Since this is not a lossy conversion, and there is no conflicting signature, the `signal` label does not give any extra clarity at call site.

Drop the label of `SignalProducer` initializers that take a sequence.

---

README.md

Per the discussion with @mdiep, here is a tentative plan on 1.0 Gold Master, and two subsequent major releases (2.0/3.0) for Swift 3.1 and Swift 4.0.
Hopefully this would help communicate the major development goals of ReactiveSwift towards Swift 4.0, and help depending libraries and users with time constraints planning adoptions/migrations ahead.
:shipit: 
Any comment is appreciated!
/cc @ReactiveCocoa/reactiveswift

Release Roadmap

---

Sources/Signal.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

Fixes #135 and #136.
As described in #136, and demonstrated by [the test case](https://github.com/ReactiveCocoa/ReactiveSwift/pull/137/commits/2d239c50e1b97b95874f5c52e9cdc43a5d11a299):
> 1. A strong release atomically drops the refCount to 0. But deinitialization does not start right away.
> 2. A weak retain - the binding's observer closure in this case - manages to increment the refCount before the strong release flags the object as deallocating.
> 3. The deinitialization is thus delayed until exiting the scope of the observer closure, i.e. within the sendLock.
In the context of binding:
```swift
signal
.take(during: target.lifetime)
.observeValues { [weak target] value in
target?.consume(value)
}
```
```
Thread 1             |            Thread 2 …
```

Allow all termination events to be recursively sent.

---

Sources/Action.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

Make `Action` retain its state property.

---

Documentation/BasicOperators.md
ReactiveSwift.xcodeproj/project.pbxproj
Sources/ResultExtensions.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

I think these make a lot of sense now that we have `AnyError`, and should make it much more natural to work with code that uses Swift error handling.

Add throwing versions of attempt(_:) and attemptMap(_:)

---

Sources/Signal.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

This is in part inspired by the API Design Guidelines: https://swift.org/documentation/api-design-guidelines/#label-closure-parameters.
Attempts to clarify usage by being more explicit about the input and output ends of the signal "pipe", and rewords the documentation accordingly.

Proposal: Label the output and input ends of Signal.pipe()

---

Sources/Deprecations+Removals.swift
Sources/Disposable.swift
Sources/Flatten.swift
Sources/Scheduler.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/DisposableSpec.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift

`SerialDisposable.innerDisposable` -> `SerialDisposable.current`.
`ScopedDisposable.innerDisposable` -> `ScopedDisposable.wrapped`.

Rename `innerDisposable` to `inner`.

---

Sources/Property.swift
Sources/UnidirectionalBinding.swift

```swift
if let disposable = disposable {
target.lifetime.ended.observeCompleted { disposable.dispose() }
}
```
would leave the disposable of a disposed binding in the lifetime signal forever (until the lifetime ends).
I also notice one thing — `observe` would show up in the code completion of `Property` and `SignalProducer`, but neither use this term. Perhaps it would be better to rename it to `bind(_:during:)`.

Fixed the unbound memory growth of unidirectional bindings.

---

.gitignore
.jazzy.yaml
.travis.yml
Documentation/ReleaseProcess.md
Sources/Action.swift
Sources/Atomic.swift
Sources/Bag.swift
Sources/Reactive.swift
Sources/Signal.swift
Sources/SignalProducer.swift
script/gen-docs
script/latest-index.html.template

Enabled by [Jazzy](https://github.com/realm/jazzy).
Docs would be accessible at: http://reactivecocoa.io/reactiveswift/docs/latest/. CI would generate documentations with tag-triggered builds, and open a pull request in ReactiveCocoa.github.io with @ReactiveCocoaCI.

Automated documentation generation via CI.

---

Documentation/BasicOperators.md

I caught an example that was still assuming the semantics of a cold signal after the migration to use hot signals (`Signal`).

[skip ci] Minor fixes in documentation

---

CodeOfConduct.md

Adapted from the Contributor Covenant. Linked by the Slack self-signup page.

Community Code of Conduct

---

Sources/Deprecations+Removals.swift
Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

Fixes #198. Originally suggested in #197.

Deprecate strategy and remove `NoError` constraint from `flatten` when the value is a `Sequence`

---

README.md

The type was also `Void`, which doesn’t makes sense, since you apply an ID (`.apply(snackId)`)

Based on an ID (input), it yields a Snack (Output).

---

Sources/EventLogger.swift

Unfortunately, since Swift dropped named arguments on closures, Xcode provides no clues as to what they are.
All you can see when opening the compiled framework on Xcode is:
```swift
/// A type that represents an event logging function.
public typealias EventLogger = (String, String, String, String, Int) -> Swift.Void
```
So hopefully this will make it a bit easier to use.

Improved docs on EventLogger

---

Sources/Action.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

Fixes #220.
There is a potentially circular relationship between `Action.isEnabled` and `Action.isExecuting`. It's valid for users to observe properites on `Action` and feed the output back into the action state, and in turn influence `Action.isEnabled`.
This resolves an issue where:
1. The user supplies a condition as the action enabled state
2. Any property derived from the internal `Action.state` is observed
3. Synchronously, the observer updates the user-supplied state property
4. Which updates the internal `state` property
5. Which causes an externally-observable event to fire, returning to (3), indefinitely.
The reason for this manifesting as an infinite loop, rather than an infinite recursion, is the internal use of a `replayLazily` in `Property`: each time a side effect on the …

Fix infinite feedback loop between Action states

---

Sources/Property.swift

Fixes #213. This more closely matches the documentation for the other methods.

Fix `map` documentation

---

Sources/Scheduler.swift

Related: https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20161205/004147.html
> _Joe Groff jgroff at apple.com_
> If you apply them to memory you allocated manually with malloc/free on UnsafeMutablePointer's allocation methods, then yeah, they should work as they do in C. That's the safest way to use these functions today. Passing a Swift `var` inout to one of these functions does not guarantee that accesses to that var will maintain atomicity, since there may be bridging or reabstracting conversions happening under the hood.

[Internal] Manually allocate memory for the atomic counter in UIScheduler.

---

Sources/SignalProducer.swift

`block` is an Objective-C term.

Rename a parameter of a `SignalProducer` initializer.

---

Sources/Deprecations+Removals.swift
Sources/FoundationExtensions.swift
Sources/Scheduler.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Sources/UnidirectionalBinding.swift

Since there isn't a name conflict, the protocols should drop the suffix per the Swift API Guidelines. The renaming is source compatible.

Rename scheduler protocols.

---

Sources/Action.swift
Sources/Lifetime.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/LifetimeSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

1. New methods and operator: ~~`attach`,~~ `observeEnded` ~~and `+=`~~.
`ended` provides a full `Signal` interface that is overblown for the general use cases of `Lifetime`.
1. [Bugfix?] Safe observation ~~& deprecating `Lifetime.ended`.~~
`ended.observeCompleted` does not handle the observations to a terminated `ended` Signal, and the action is simply ignored.
[It should have been invoked regardless](https://github.com/ReactiveCocoa/ReactiveSwift/pull/229/files#diff-66075186b734efda335ddf4d9c209017R62), like how adding a `Disposable` to disposed `CompositeDisposable` would dispose of the disposable being added.
~~Composition of `Lifetime` is suggested to be done through lifetime operators instead, e.g. `and` and `or`, should the demand arise.~~

`Lifetime.observeEnded` and `take(during:)` fix.

---

Sources/Scheduler.swift

After changing some parameter names for scheduler instance methods markup reported "No description" for those parameters. This PR fixes the issue.

Fix scheduler's markup documentation

---

ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Contents.swift
Sources/ValidatingProperty.swift
Tests/ReactiveSwiftTests/ValidatingPropertySpec.swift

Pros
1. `ValidatingProperty` is shorter.
1. A hypothetical "read-only" `ValidatingProperty` is essentially a pass-thru wrapper plus a `Property<ValidationResult>`. Moreover, it can be named as *validated* property instead.
Cons
1. `Validating` does not strongly imply `Mutable`. But having a `Mutable` prefix is not really important IMO, unless there is a clash in name or semantics.

Drop the `Mutable` prefix of `MutableValidatingProperty`.

---

ReactiveSwift.podspec

Suppress all warnings when building with the Release configuration, so that the internal deprecation warnings would not be visible when ReactiveSwift is built using ~~Carthage and~~ CocoaPods.
SwiftPM does not provide a way to pass compiler flags, so it won't be covered by the patch.
Usage: #248, #254

Suppress all warnings when building with CocoaPods.

---

Sources/Observer.swift

Anonymous closure and instance method reference are predominantly used as observers to `Signal`s. `ObserverProtocol` ideally would be instead interoperating different _types_ as an observer, which doesn't seem a capacity that is demanded for.
It hasn't been in use for years either.

Deprecate `ObserverProtocol`.

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Action.swift
Sources/Deprecations+Removals.swift
Sources/Property.swift
Sources/UnidirectionalBinding.swift
Tests/LinuxMain.swift
Tests/ReactiveSwiftTests/DeprecationSpec.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

Related: #241
Just the implementation. Should appear as the same to general end users.
1. Renaming: `BindingSource` and `BindingTargetProvider`.
1. `BindingTargetProvider` now requires all conforming type to return a concrete `BindingTarget`. Moreover, `BindingTargetProvider` is no longer class bound.
1. The special mechanic for `BindingTarget` has been removed with (2) in place.

Reformulate unidirectional binding protocols.

---

ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Contents.swift
Sources/ValidatingProperty.swift
Tests/ReactiveSwiftTests/ValidatingPropertySpec.swift

* `success` becomes `valid`.
* `substitution` becomes `coercedValid`.
* `failure` becomes `invalid`.
The names were taken directly from [Cocoa Bindings and Key Value Validation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CocoaBindings/Concepts/MessageFlow.html#//apple_ref/doc/uid/TP40002149-BCICADHC). The main concern from me which drives the change is that the word `substitution` is _ambiguous_, while it in fact mimics the "coerced valid value" in Key Value Validation.

Rename the result enum cases of validating property.

---

Sources/Atomic.swift

Swift 3.1 beta complains that these methods are not qualified to have `@inline(__always)` because `value` is not public:
> Atomic.swift:65:42: Let 'value' is private and cannot be referenced from an '`@inline(__always)`' function
Since `@inline(__always)` is not officially supported, this needs to be fixed here, rather than in Swift. See [here](https://bugs.swift.org/browse/SR-4013?focusedCommentId=21981&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21981).
Related commit in Swift:
https://github.com/apple/swift/commit/50b5d01dd7a023b4d7c7a77019c1c26ee507da03
According to that commit message, it seems that `@inline` is now only for public, resilient API.

Remove unnecessary `@inline`

---

Sources/Atomic.swift
Sources/Deprecations+Removals.swift

Justification
1. The protocol has little value other than sharing implementations of atomic operators, if we assume different implementations mean different lock semantics.
2. Potential optimizations would require knowledge to the storage, which cannot be exposed through the protocol. The apparent way for these would be enum storage + concrete same type extensions.

Deprecate `AtomicProtocol`.

---

Sources/Action.swift
Sources/Atomic.swift

...instead of removing it completely. See the discussion on #245 for context. I'm proposing this change as an alternative for discussion: there are some issues with this approach, so I thought it would be good to have something concrete to discuss.
Benefits:
- Mergeable into master now, suitable for inclusion in the next minor release.
- `ActionProtocol` is an implementation detail, but isn't clearly documented as such. There are possibly users making use of it in ways we didn't intend (I was once one of them).
**Update:** See https://github.com/ReactiveCocoa/ReactiveSwift/pull/248#issuecomment-277496797.
<strike>
Downsides:
- Because conditionally compiled code has to be syntactically valid, we essentially have to duplicate the extension. I experimented with using an internal typealias …

Pitch: Deprecate ActionProtocol

---

Sources/Deprecations+Removals.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

An unfortunate inconsistency that has already been shipped. 😅
Anyhow, it is renamed to `negate()` so that like its zero-arg operator friends, it gives a visual weight and sense of being factory, rather than being a cheap computed/stored value.

Rename `negated` to `negate()`.

---

.gitignore

If you use Carthage to include ReativeSwift in your project and you
check your `Carthage/Checkouts/` folder into git,
when `ReativeSwift.xcworkspace` is missing, you get a general "Build
Failed" error from Carthage. The problem is that, somehow the
`xcworkspace` is missing. However, there's no info from git since
`xcworkspace` is ignored in ReativeSwift's `.gitignore` file.
ReativeSwift does check in `ReactiveSwift.xcworkspace` file in git. This should
have no impact on the project. Hopefully this will make debugging
the Carthage build error mentioned above easier.
PS.
I spent a few hours on a Sunday morning pulling my hair out trying to figure out why Carthage wouldn't build my dependencies and then figured this out. Today, my teammate also ran into this problem.

Remove `*.xcworkspace` in .gitignore

---

Sources/Atomic.swift
Sources/Disposable.swift
Sources/Flatten.swift
Sources/Lifetime.swift
Sources/Property.swift
Sources/Reactive.swift
Sources/Scheduler.swift
Sources/Signal.swift
Sources/SignalProducer.swift

- `Signal`, `SignalProducer` & `Scheduler` classes have preconditions
documented;
- added a note about how `DisposableHandle` instances can be created;
- added missing `/` to `Reactive` initialiser's documentation;
- added missing documentation to `Atomic`'s transition methods;

Update documentation markup

---

Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

Implements #297.
`concat` and `merge` are now aliases of `concurrent(limit: 1)` and `concurrent(limit: .max)`, respectively. The iterative process to start producers is preserved.
**WIP:**

Introduce `FlattenStrategy.concurrent`.

---

Sources/Deprecations+Removals.swift
Sources/EventLogger.swift
Sources/Flatten.swift
Sources/Optional.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/TestError.swift

`SignalProducer` heavily intertwines with `Signal` at its core, while both `SignalProducer` and `Signal` are already pretty generic with refinements & specialisation enabled through closures & type erasure, IMO mitigating the need of another hot signal type. Moreover, `Property` is not going to conform to either of them due to clashes in base names, even assuming the presence of higher-kinded types in Swift.
So with all these, I do not envision any value of semantic abstraction from these protocols.
The PR does not remove `SignalProtocol` and `SignalProducerProtocol` however, since they are still necessary for constraining flattening operators until we have parameterised extensions.

Move Signal and SignalProducer operators to the concrete types.

---

Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Implemented https://github.com/ReactiveCocoa/ReactiveSwift/issues/138.
Ref: [ReactiveX - Amb operator](http://reactivex.io/documentation/operators/amb.html)
I'm still wondering whether `.first` is really a good naming since there's already a blocking `func first()`.
I personally feel `race` is a better name.

Add `FlattenStrategy.race`

---

Sources/Atomic.swift
Sources/Disposable.swift
Sources/Signal.swift
Sources/SignalProducer.swift

Make `returns:` delimiter contain documentation on same line.

Minor documentation markup update

---

Tests/ReactiveSwiftTests/FlattenSpec.swift

The producers may be started asynchronously. So these expectations have to be asynchronous too.

Improved a `FlattenStrategy.concurrent` test case.

---

Sources/Deprecations+Removals.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

The very last two free functions of ReactiveSwift find their new home. Renaming fix-its work properly despite `self` being the second argument.

Move `timer` to `SignalProducer`.

---

Sources/Scheduler.swift

Every `Scheduler` has an identity.

Give `Scheduler` a class bound.

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Follow-up to #304.
`then(_:)` is disambiguated by introducing two more specific variants.

Move `SignalProducerProtocol.then` to the concrete type.

---

Sources/Deprecations+Removals.swift
Sources/Property.swift

... and also `ComposableMutablePropertyProtocol.withValue(_:)`.
It breaks the conformances, but the impact should not be large given its recent introduction in ReactiveSwift 1.1. Call sites are migrated.

Remove the label from `MutableProperty.withValue(_:)`.

---

Sources/Bag.swift
Sources/Deprecations+Removals.swift
Sources/Disposable.swift
Sources/Signal.swift
Sources/SignalProducer.swift

1. Rename `RemovalToken` to `Bag.Token`. This could be source breaking, since `Bag` has to be parameterised.
1. Replace the token object with a monotonic `UInt64` timestamp. In other words, `Bag` itself no longer incurs an ARC overhead except for its `ContiguousArray` storage. This improves the performance in iterations and copying.
1. Store the elements and the tokens in SoA form, improving cache locality in iterations and token searching during removals. That said best case removals seem to be affected by this change.
1. Exploit the timestamps to accelerate average case removals via binary search.

`Bag` improvements.

---

Sources/Property.swift
Sources/UnidirectionalBinding.swift

1. Replace the `observe(_:during:)` requirement in the `BindingSource` protocol with a `SignalProducer` representation.
If #351 is accepted, `BindingSource` would adopt arbitrary constraint on associated types and conditional conformances in Swift 4:
```swift
public protocol BindingSource: SignalProducerRepresentable where Error == NoError {}
extension SignalProducer: BindingSource where Error == NoError {}
// ... etc.
```
While this is breaking, `observe(_:during:)` is not expected to be publicly used.
1. Move `<~` into `BindingTargetProvider`.
The `SignalProducer` representation and the `BindingTarget` are sufficient points of customisation, and apparently there would not be an alternative semantic of `<~` to override for in the context of these two protocols.

Tweak unidirectional binding protocols.

---

Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Rationale: https://github.com/apple/swift-evolution/blob/master/proposals/0171-reduce-with-inout.md

Add inout variants of `reduce` and `scan`

---

Sources/Property.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

`Property` is supposed to emit only `Event.value` or `Event.complete`. However, `Property` constructed from an initial value and a signal or a producer would pass through and replay the `interrupted` event at the moment. This PR maps `interrupted` into `completed` for these circumstances.
A minor refactoring in `MutableProperty` is applied to take advantage of the new private `Observer` initialiser.

Fixed rare occurences of `interrupted` emission in `Property`.

---

Sources/Atomic.swift
Sources/Signal.swift

As mentioned in #282, `os_unfair_lock` is generally faster all-around (slightly when uncontended, significantly when contended), since it does not need to maintain fairness among waiting threads.
~~This branch is a transitional implementation purely in Swift, until eventually Swift supports availability propagation of enum cases to switch case scopes.~~
~~Related: [SR-4079](https://bugs.swift.org/browse/SR-4079)~~
`Lock` is an abstract base class of two implementations: `UnfairLock` and `PthreadLock`. When constructing a lock through `Lock.Type.make`, it picks the implementation with `#available` runtime checks.
It turns out that virtual dispatch (subclassing) is still pretty fast, and is certainly faster than the implementation of the #282 trick in pure Swift, which requires per-instance …

Unfair Lock, take 2

---

Sources/Deprecations+Removals.swift
Sources/Disposable.swift
Sources/Flatten.swift
Tests/ReactiveSwiftTests/DisposableSpec.swift

Cherry-picked from #334.
Use `ActionDisposable` instead, akin to `Signal.observe`.

Remove `CompositeDisposable.DisposableHandle`.

---

Sources/Deprecations+Removals.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift

1. Follow the Swift API Guidelines and the Standard Library in naming closure parameters according to their assertions or roles, instead of generic names like `predicate`. e.g.
```
-	public func filter(_ predicate: @escaping (Value) -> Bool) -> Signal<Value, Error> {
+	public func filter(_ isIncluded: @escaping (Value) -> Bool) -> Signal<Value, Error> {
```
1. Remove the label of a `SignalProducer.attempt` overload, which is supposed to be a parameter name.
1. Condense a few pieces of documentations by taking advantage of the new parameter names, while keeping another few consistent among the `Signal` and the lifted versions.

Rename closure parameter names of operators, and update documentations.

---

Sources/Atomic.swift

Related: #371
Let's play safe.

Manually allocate locks.

---

Sources/Signal.swift

Nest the signal state helper types inside `Signal`.

---

Sources/Deprecations+Removals.swift

Since 2.0 is breaking anyway, mark everything as unavailable.

Mark all deprecated symbols unavailable.

---

Sources/Deprecations+Removals.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Follow-up to #304.
The original signatures are ambiguous, but they somehow work as protocol extensions in Swift 3. Moving them to the concrete type reveals the ambiguity.
```swift
extension SignalProducer {
public static func attempt(_ operation: @escaping () -> Result<Value, Error>) -> SignalProducer<Value, Error>
}
extension SignalProducer where Error == AnyError {
public static func attempt(_ operation: @escaping () throws -> Value) -> SignalProducer<Value, Error>
}
```
Consider `.attempt { () -> Result<Int, NoError> in .success(1) }`, the closure can satisfy both methods and produce:
1. `SignalProducer<Int, NoError>`; or
1. `SignalProducer<Result<Int, NoError>, AnyError>` since non-throwing closures are covariant of their throwing version.
Renaming `SignalProducer.Type.attempt` to …

Rename `SignalProducer.Type.attempt` to `init(_:)`.

---

Sources/Property.swift

Helps when initialising `Property<U?>` with a producer or signal of `U`.

Add two convenience `Property` initializers.

---

Sources/Deprecations+Removals.swift
Sources/Flatten.swift
Sources/Signal.swift
Sources/SignalProducer.swift

Every `Signal` has only one error. Should it be `promote(_:)` though?

Rename `promoteErrors` to `promoteError`.

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

A "bug" that would materialise only with #140.
As the signal semantic of 2.0 requires the generator/input observer to be retained, the lifetime of `SignalProducer.never` should have retained its input observer.

Precautionary `SignalProducer.never` fix.

---

CHANGELOG.md
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Preceded by #408.
This is useful when combining multiple signals with `NoError` in the mix, reducing the verbosity.
```swift
let (signal, _) = Signal<(), NoError>.pipe()
print(type(of: signal.promoteError(CocoaError.self)))
print(type(of: signal.promoteError()))
print(type(of: signal.promoteError() as Signal<(), CocoaError>))
// The promotion of the second operand is inferred.
print(type(of: Signal.zip(signal.promoteError(CocoaError.self), signal.promoteError())))
```

`promoteError` type inference.

---

CHANGELOG.md
Sources/Property.swift

As a compensation, we could make `modify(didSet:_:)` a public API, but this can be considered separately.

Enforce exclusivity of access in `PropertyBox`.

---

CHANGELOG.md
Sources/Action.swift
Sources/Property.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

Related: #309.
There are legitimate uses of `isExecuting` feedback to the `Action` state property. For example, we may link the availability of multiple actions together, so that all disables when one executes.
This PR refactors the internal of `Action` so that such use cases are permitted. Legitimate infinite feedback loops would still result in deadlocks.
Example:
```swift
let isIdle = MutableProperty(true)
candyCrusher = Action(enabledIf: isIdle) { ... }
fruitCrusher = Action(enabledIf: isIdle) { ... }
carrotCrusher = Action(enabledIf: isIdle) { ... }
isIdle <~ candyCrusher.isExecuting.negate()
isIdle <~ fruitCrusher.isExecuting.negate()
isIdle <~ carrotCrusher.isExecuting.negate()
```
Could we have some kind of "action group"s that determine the availability at a coarser granularity?

Enable `Action` executing state feedback to the state property.

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

The PR proposes to overhaul how `SignalProducer` produces a new instance of `Signal`.
1. The public API of `SignalProducer` remains untouched.
1. `startWithSignal(_:)` is no longer responsible of creating the `Signal`.
1. `SignalProducer.Builder` replaces the "start handler" as the internal representation of `SignalProducer`.
The builder is responsible of creating an instance of `Signal` on request. It also creates a customised post-creation side effect and an interrupt handle for every produced `Signal`.
Unlike `startWithSignal(_:)`, the caller is responsible of invoking the post-creation side effect i.e. `didCreate`. The swap in responsibility here gives a room of optimisation for lifted `Signal` operators. They can now dodge the unnecessary relay `Signal` that would otherwise be …

Less hops in operator lifting.

---

CHANGELOG.md
ReactiveSwift.xcodeproj/project.pbxproj
Sources/Deprecations+Removals.swift
Sources/Flatten.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Implements #349.
Introduce `SignalProducerConvertible` so that n-ary producer operators may take any entity which is declared to be expressible by a `SignalProducer`.

Generic n-ary producer operators for n > 1.

---

Sources/SignalProducer.swift
Sources/UnidirectionalBinding.swift

Changes to `BindingSource` in #351 caused conformances to fail under Swift 4.

Fixes for Swift 4 2017-05-29 development snapshot.

---

Sources/Deprecations+Removals.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Sources/ValidatingProperty.swift

The changes should be compatible with Swift 3.1.

Address redundant conformance constraint warnings for Swift 4 compiler (Xcode 9)

---

CHANGELOG.md
ReactiveSwift.xcodeproj/project.pbxproj
Sources/InhabitableTypeGuards.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Raise warnings when using observation API or operators that is essentially a logic error due to `Value` or `Error` being an inhabitable type. Please refer to `InhabitableTypeGuards.swift` for the lists of affected operators.
Also note that these overloads cannot be marked as `unavailable` or `obsolete`, or otherwise the regular version would take precedence over this.

Warning for observation APIs when used with inhabitable types & `promoteValue`.

---

CHANGELOG.md
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

We should be able to use key paths with `flatMap()` too, but this is a start.

Overload map() to support key paths

---

CHANGELOG.md
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

Expected to be picked up by RAC for convenience shorthands.

BindingTarget + Smart Key Paths.

---

CHANGELOG.md
Sources/Signal.swift

Related: https://bugs.swift.org/browse/SR-5190 with the kind help from @gparker42.
The changes we made to `AliveState` in #355 clash with #354, causing heap corruptions when `Signal` is under concurrent stress tests in ReactiveCocoa.
I have re-run the concerned RAC stress tests with fairly large number of iterations, and the issue is patched by this fix.

Fixed an impedance mismatch between Signal.Core RCU and Bag.

---

CHANGELOG.md
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Note that `combinePrevious()` is not implemented using default arguments and optionals, so that existing use cases as concerned by @NachoSoto would not break.
In other words, `combinePrevious(nil)` and `combinePrevious()` are not equivalent, given the constraint `<U> Value == Optional<U>`.

A variant of `combinePrevious` that doesn't need an initial value.

---

CHANGELOG.md
Sources/Action.swift
Sources/Deprecations+Removals.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

There are currently two options for using some property as state for an `Action`:
- Use the designated initialiser `Action.init(state:enabledIf:executing:)` (the most complicated);
- Use the various convenience initialisers defined for `Void` input types, which are nice but sacrifice the ability to use a custom input type.
This change rounds out the set of convenience initialisers for maximum flexibility:
- You can now use a state-property with a non-`Void` input type, without having to worry about `enabledIf`;
- You can use a conditionally-unwrapped optional state-property in the same way.
In order to unambiguously differentiate between the optional and non-optional variants in all cases, all the optional versions now use `unwrapping` as the parameter label for the state-property: …

Revisit Action state-property convenience initialisers

---

Sources/Signal.swift

Preceded by #453.
Let's look at how the compiled assembly does the work:
```swift
Thread A                           | Thread B
------------------------------------------------------------------
Lock `updateLock`.                 |
|
Pack the new enum.                 |
(with retain)                      |
|
Load the current `self.state`.     | Load `self.state`.
|
Store to `self.state`.             | Retain the enum.
|
Release the old enum.              | Call the observers.
|
Unlock `updateLock`.               |
```
It seems safe, especially since writes are serialised.
But what if we shift the timeline of thread B a little bit further?
```swift
Thread A                           | Thread B
------------------------------------------------------------------
Lock `updateLock`. …
```

Improve `Signal` state management to avoid an ARC race.

---

script/gen-docs

Markdown files with dots before `.md` are now covered.

Update the relative link regex in `gen-docs`. [skip ci]

---

Sources/Flatten.swift

In case we might want to add new flatten strategies in the future without a major version bump, `FlattenStrategy` now hides its enum nature. This on paper breaks switches over `FlattenStrategy`, but I don't see any real use case that would be affected.

Extensible FlattenStrategy.

---

CHANGELOG.md
Sources/Deprecations+Removals.swift
Sources/ValidatingProperty.swift
Tests/ReactiveSwiftTests/ValidatingPropertySpec.swift

Nesting the result and the output type into ValidatingProperty.

---

CHANGELOG.md
Sources/Observer.swift
Sources/Signal.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Send `interrupted` when an input observer deinitializes.

---

CHANGELOG.md
Sources/Signal.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Fixes #470.
Removed also a stale test case.
The deadlock happens when a `value` event of a combined signal triggers termination of one of its source signals (except for the one that indirectly yields the `value` event).
Example: https://github.com/ReactiveCocoa/ReactiveSwift/pull/471/files#diff-8c46f2726f3ee5a6dbf7ad24b29dbd57R2795
The value from `B` yields a new `(A, B)` tuple, leading to termination of `A` and eventually informing the strategy with the completion of `A`. Since the delivery of the tuple is in progress, the strategy's internal lock is still acquired, resulting in the deadlock.
Threading of the signal aggregate strategies now mirrors that of `Signal.Core` to allow recursive termial event sent by a `value` event.

Fixed a deadlock upon disposal in AggregateBuilder.

---

Documentation/BasicOperators.md

Hi, it's me again 👋
I found a couple of method signature errors in BasicOperators.md when I was trying the code snippet out in Sandbox.playground. Thanks!

Fix method signature errors in BasicOperators.md

---

Sources/UnidirectionalBinding.swift

`WritableKeyPath` supports leaves with value semantics, and is the superclass of `ReferenceWritableKeyPath`.

Use `WritableKeyPath` instead of `ReferenceWritableKeyPath`.

---

CHANGELOG.md
Sources/Action.swift
Sources/Property.swift
Tests/ReactiveSwiftTests/ActionSpec.swift

Expand the feedback support for `Action.isExecuting` in #400 to `Action.isEnabled`. The nasty `didSet` thingy in `PropertyBox` and `MutableProperty` has also been cleaned up.

Expand feedback support to `Action.isEnabled`.

---

Sources/FoundationExtensions.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift

In Swift 3.2, `Dispatch.DispatchTimeInterval` has a new case, `.never`, that needs to be switched on.
Fixes https://github.com/ReactiveCocoa/ReactiveSwift/issues/483.

Xcode 9 beta 3 Support

---

Documentation/APIContracts.md
Documentation/ReactivePrimitives.md

Hi ReactiveSwift team,
This PR fixes 2 typos and a link. Please check it out. Thanks!

Fix typo and link in documentation

---

.travis.yml
Sources/FoundationExtensions.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift

While working on a server-side project I noticed that neither of the latest 1.1.x or 2.x releases would build for me on Linux with the latest 4.x snapshots (2017-07-11 and 2017-07-13 as of this writing). Turns out the `DispatchTimeInterval` enum change isn't available there (yet?)
I'd like to think that this will be unnecessary in a future Swift snapshot on Linux, but perhaps it's worth integrating this small fix so that the release candidates aren't busted until that happens.

Correct some Linux-specific build issues

---

CHANGELOG.md
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

I implemented #224 and write test code
I'm new to this. Is this correct? 
Please review in your free time.

Add retry(upTo:interval:on:)

---

CHANGELOG.md
Sources/Property.swift

Swift 3 compiler is less performant in situations that need sophisticated inference. It appears not to be an issue for Swift 4 though. 💁‍♂️ 
While the constraints have been tightened, IMO it shouldn't be considered API breaking, since the `Property` requirements mandate `NoError`, and the `Error` associated type is just an implementation detail that is always `NoError` at conformance time.
Ideally we would get rid of these in RAS 3.0 by constraining `PropertyProtocol` with `Error == NoError`.

Address the exceptionally high build time.

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

See https://github.com/Carthage/Carthage/pull/2077#discussion_r129483994 and https://github.com/Carthage/Carthage/pull/2077#discussion_r129484077.

Add `SignalProducer.init` overloads for `NoError`

---

Documentation/FrameworkOverview.md

Scheduler Protocol is now just called `Scheduler` instead of `SchedulerProtocol`: https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Scheduler.swift#L17

Framework Overview

---

Package.swift

There are two independent changes here:
1. Use `NSString.boolValue` in `Package.swift` to parse the
`SWIFTPM_TEST_ReactiveSwift` environment variable for a truthy value. This
is cross-platform, and handles more truthy values like `true` and `1`, which is
nice.
2. Use a more general `SWIFT_PACKAGE_TEST` environment variable. I introduced
this in https://github.com/sharplet/Regex/pull/53, and like the idea of
having a more standard variable name that can be used across different
projects.
I think (1) is a nice improvement, and would love some input on (2) as a potential standard variable name. What do you think?
- N/A: ~Updated CHANGELOG.md.~

swiftpm test dependency updates

---

ReactiveSwift.xcodeproj/project.pbxproj

This (should be) a very minimally invasive PR. 
**The background:**
In general, Xcode appears to behave very badly when using workspaces and its "Find Implicit Dependencies" feature in the scheme editor. Many folks throw up their hands and resort to manual dependency specifications.
Well I think that its terrible behavior can be attributed to a bug in Xcode that causes it to not update the `productName` value in the `.pbxproj` file when a target is renamed. This happens very commonly when creating a framework project, then duplicating the framework targets with suffixes for other platforms.
For some folks, this patch may improve their build experience in Xcode quite a bit—especially for follks like me with very large workspaces that involve a lot of subprojects.
Sorry it took so long to …

Fix bad productName values

---

CHANGELOG.md
Sources/Atomic.swift
Sources/Disposable.swift
Sources/Event.swift
Sources/Observer.swift
Sources/Signal.swift
Sources/SignalProducer.swift

Taking advantage of the deferred nature of `SignalProducer` to further reduce the overhead.
1. Composing `SignalProducer` is going to be _way, way_ cheaper than composing `Signal`.
1. Constant `SignalProducer`s, e.g. `init(value:)` and sequence `init(_:)`, are going to do _significantly_ less work.
1. There is still a ~16x overhead over standard library `lazy` for purely collection manipulation. But given the type erasing and reactive (passive) nature of FRP/ReactiveSwift, there is probably very little stuff we can do about it. IOW optimizing for this is a non-goal. :)
The actual speedup is subject to the new internal API adoption — unmigrated `SignalProducer` operators would still be relying on the conventional behavior and/or `lift`.
For example, if you do:
```swift …
```

Cutting the SignalProducer overhead further.

---

Sources/Event.swift
Sources/Observer.swift
Sources/Signal.swift
Sources/SignalProducer.swift

The requirement of `SignalProducerCore.start` has been changed slightly, so as to support `TransformerCore` yielding terminal events from value events.
It intercepts the output of the combined event transformation to:
1. interrupt the upstream when appropriate; and
2. ensure only one terminal event would ever be delivered.
The overhead should be per block of contiguous applications of `TransformerCore` operators.
Using `master` for this new `take(first:)` (#487) causes the `SignalProducer.repeat` test case to fail with stack overflow.
```swift
SignalProducer<Int, NoError>(value: 1)
.repeat(.max)
.take(first: 1)
.start()
```
This is because the `TransformerCore` implementation in `master` is not designed in mind with transformations that could yield terminal events. So even if `take(first: …

Improve TransformerCore and move `take(first:)`.

---

CHANGELOG.md
Sources/Atomic.swift

https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3507
`pthread_mutex_trylock` somehow returns `EAGAIN` on 32-bit ARM devices when the mutex is configured to be error checking. It should either succeed or return `EBUSY` according to the documentation.

Fixed a pthread issue in 32-bit ARM debug builds.

---

Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift

Migrate operators to be event transforms, and adopt `TransformerCore` in their `SignalProducer` variants.
1. `materialize`;
1. `dematerialize`;
1. `skipNil`;
1. `skip(first:)`;
1. Two variants of `collect`;
1. `observe(on:)`; and
1. `delay(_:on:)`.
~~Updated CHANGELOG.md.~~

Migrate operators. Part II.

---

Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift

* `attemptMap`;
* `attempt`;
* `take(last:)`;
* `take(while:)`;
* `skip(while:)`;
* `combinePrevious`;
* `scan`;
* `reduce`;
* `skipRepeats`;
* `uniqueValues`;
* `promoteError`; and
* `promoteValue`.
* `reduce` has a new implementation that doesn't need `Signal`.
* `skipRepeats` has a new implementation that uses one switch, instead of four operators.

Migrate operators Vol III.

---

CHANGELOG.md
Sources/Action.swift
Sources/Flatten.swift
Sources/Observer.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift

`Signal.Observer.action` does not capture the `Signal.Observer` it derived from. This might cause issues with `Signal` inputs and transformed observer, since these rely on the lifetime of the `Signal.Observer`. This also implies a semantic inconsistency between `action` and any method reference to `send*`.
While patching `Observer.action` is sufficient, it appears to be a great opportunity to hide the closure as an implementation detail, and complete the `send` method family with a new overload taking the event sum type.

Replace `Observer.action` with `Observer.send`.

---

CHANGELOG.md
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Personally I'd use it to return the `Disposable` given to the block, so that I have an interruption handle for the started producer, similar to the other `start()`-methods.
By using `@discardableResult` we retain backwards-compatibility without causing warnings about unused return values.
``` swift
let disposable = producer.startWithSignal { signal, disposable in
// …
return disposable
}
```
_Note: I have not discussed this feature with anybody beforehand, but the change was easy enough so I wrote it and submitted a PR_

Make `startWithSignal()` return the result of `setup(…)`.

---

.gitignore
Sources/Observer.swift
Sources/Property.swift
Sources/Scheduler.swift
Sources/Signal.swift
Sources/UnidirectionalBinding.swift

Remove redundant constraints.

---

Sources/Property.swift

1. Remove the unused `transform`.
2. Replace the unnecessary use of `startWithSignal` with `start`, so that composed property can take advantage of the recent `SignalProducer` changes.

Tweaked the composed property event delivery.

---

CHANGELOG.md
Sources/Deprecations+Removals.swift
Sources/Flatten.swift
Sources/FoundationExtensions.swift
Sources/Lifetime.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Follow-up to #334.
This is not as trivially migratable as #334, since `Signal` had a different design choice in the signal generator closure than the `SignalProducer`. Let alone the fact that [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md) is not implemented in Swift 3, adding obstacles to automatic migration.
1. Change the `Signal` generator signature to `(Observer, Lifetime) -> Void`, so that it matches the style of `SignalProducer.init`.
```swift
let signal = Signal { observer, lifetime in
let disposable = self.observe { ... }
_ = (disposable?.dispose).map(lifetime.observeEnded)
}
let producer = SignalProducer { observer, lifetime in
let disposable = producer.start { ... }
lifetime.observeEnded(disposable.dispose)
}
```

Signal resource management with `Lifetime`.

---

CHANGELOG.md
Sources/FoundationExtensions.swift
Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift

- Fixed integer overflows for Foundation extensions (#506)  …
- Added overflow test case
- Removed note on value limits for DispatchTimeInterval `*` operator

Fixed integer overflows for Foundation extensions

---

Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift

Migrated operators:
1. `throttle(_:on:)`;
2. `debounce(_:on:)`;
3. `SignalProducer.negate`;
3. `SignalProducer.and`; and
3. `SignalProducer.or`.
A note on the current requirements for an operator to drop down to event transformation has been added.

Migrate operators Vol IV.

---

CHANGELOG.md
Sources/Flatten.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

Given that `SignalProducer` already supports concatenating a value or a signal, being able to concatenate an error seemed logical. I personally found this useful when implementing a signal that defaulted to an error if nothing matched a filter. For example:
```
filtered.concat(error: notFound).take(first: 1)
```

Concat error

---

Documentation/FrameworkOverview.md
ReactiveSwift.playground/Pages/Property.xcplaygroundpage/Contents.swift

Replace BindingTargetProtocol with BindingTargetProvider in doc

---

CHANGELOG.md
Sources/Event.swift
Sources/Observer.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

The issue apparently exists since 2.0 with producer lifting optimisation (#140), and is also applicable to `TransformerCore`.
With a terminated upstream, manual interruption of time shifted producers, including `delay`, `observe(on:)`, `throttle`, `debounce` and `lazyMap`, would be ignored.
This is due to the operator lifting scheme introduced in #140, which blatantly assumes the upstream always lives longer than the downstream & therefore is always available to handle the downstream/user interruption.
Simple example:
```swift
// Completed upstream + `delay`.
SignalProducer.empty
.delay(10.0, on: QueueScheduler.main)
.startWithCompleted { print("Value should have been discarded!") }
.dispose()
// Console(t+10): Value should have been discarded!
```
The first part of the fix establishes a …

Fixed a scenario of downstream interruptions being dropped.

---

Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift

So that it abides to the _interruption on specified scheduler_ rule exhibited by its peer async operators.
- ~Updated CHANGELOG.md.~

Implement `lazyMap` as an event transformation.

---

CHANGELOG.md
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift

Addresses #582. Retain timers in `QueueScheduler` so that they will not be cancelled if the user doesn’t retain the returned `Disposable`.
Note that the test leaks a timer, but I'm not sure how else to test that the timer continues running even when the `Disposable` is not retained.

Fix `schedule(after:interval:leeway:)` disposal

---

CHANGELOG.md
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Refer #597
For example, use as below.
```swift
let (signal, observer) = Signal<String, NoError>.pipe()
let triggerSignal = signal.map(to: ())
triggerSignal.observeValues {
print("trigger `value` events")
}
```
I want to add `@autoclosure @escaping`, but occur an error(`Ambiguous reference to member 'map`) on overload `map`.
So, I propose to name it `replace(to:)`, like below.
```swift
public func replace<U>(to value: @autoclosure @escaping () -> U) -> Signal<U, Error> {
return map { _ in value() }
}
```

Add map(to:) operator

---

CHANGELOG.md
Sources/Flatten.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift

Refer https://github.com/ReactiveCocoa/ReactiveSwift/issues/597

Add merge(with:) operator

---

CHANGELOG.md
Sources/Property.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

A `filter` operator for `Property` has one edge case: `Property` always needs to have a value, but what if the predicate excludes the current (or all) values of the source `Property`? 
Probably thats the reason that this operator was not yet included for Property?
I suggest to provide an initial value for the filtered `Property` to handle that case.

Add Property.filter

---

Sources/Bag.swift

1. Simplify nested code of `Bag.remove(using:)`
Use `Sequence.first(where:)`
Can be expected to gain a benefit from future Swift performance improvements by using the standard API.
2. Not use `revert()` for removing elements from bag.
Improve dispose efficiency in `CompositeDisposable`.
~- [ ] Updated CHANGELOG.md.~

Bag performance

---

CHANGELOG.md
Sources/Bag.swift
Sources/Disposable.swift
Tests/ReactiveSwiftTests/BagSpec.swift
Tests/ReactiveSwiftTests/DisposableSpec.swift

Hi✋ 
I made it possible to create Bag with initial elements, and CompositeDisposable also improved accordingly.
Probably conflicts with #608, but I fix after either is merged.

Create Bag with initial elements

---

CHANGELOG.md
Sources/ResultExtensions.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

This implements the suggestion in #409

Add conformance to SignalProducerConvertible for Result

---

CHANGELOG.md
Sources/Flatten.swift
Sources/SignalProducer.swift

Make `SignalProducer.merge` to accepts n-ary generic type that conformed to `SignalProducerConvertible`.
If this is acceptable, how about to write high-arity operators(merge,zip, and combineLatest) into files like `Merge.swift`?

[Proposal] Merge SignalProducerConvertibles

---

Sources/Bag.swift

This is continuation of https://github.com/ReactiveCocoa/ReactiveSwift/pull/602
This simplifies the implementation and gave the performance improves 2~3x.
Benchmark:
```swift
func testIteration() {
let count = 10_000_000
var bag = Bag<Int>()
for i in 0..<count {
bag.insert(i)
}
XCTAssertEqual(bag.count, count)
measure {
var trash = [Int]()
trash.reserveCapacity(count)
for i in bag {
trash.append(i)
}
XCTAssertEqual(bag.count, count)
XCTAssertEqual(trash.count, count)
}
}
```
Result:
Higher performance can be expected by dropping the overflow checking.
There is no much impact on performance, but this would be better, because `Token.value` doesn't assume overflow.
Benchmark:
```swift
func testRemoving() {
let count = 10_000
measure {
var bag = Bag<Int>()
var tokens = …
```

Bag optimization

---

Sources/UninhabitedTypeGuards.swift

Currently, compiler warns `Ambiguous reference to observeValues` when use `observeValues` of `Signal` that with an error type which is not `NoError`.
This is a confusing API.
I think it should better warn to use observeResult.
relevant issue: https://github.com/ReactiveCocoa/ReactiveSwift/issues/598
~- [ ] Updated CHANGELOG.md.~

Explicitly warning that cannot observe with ignoring the errors.

---

Package.resolved
Package.swift

I noticed that the `Package.swift` definitions did not match those of the `Cartfile`s while working on a server-side project that imported the latest release of `Result`.

Update Package.swift to match Cartfile

---

CHANGELOG.md
Sources/Reactive.swift

Make non-class types be able to conforms to ReactiveExtensionProvider

---

CHANGELOG.md
Sources/Flatten.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Continuation from https://github.com/ReactiveCocoa/ReactiveSwift/pull/610
These operators now accept `SignalProducerConvertible` conforming types.
`SignalProducer.merge(with:)`
`SignalProducer.concat`
`SignalProducer.prefix`
`SignalProducer.then`
`SignalProducer.and`
`SignalProducer.or`
`SignalProducer.zip(with:)`
`SignalProducer.sample(with:)`
`SignalProducer.sample(on:)`
`SignalProducer.take(until:)`
`SignalProducer.take(untilReplacement:)`
`SignalProducer.skip(until:)`
`SignalProducer.flatMap`
`SignalProducer.flatMapError`
`SignalProducer.combineLatest(with:)`
`Signal.flatMap`
`Signal.flatMapError`
`Signal.withLatest(from:)`
`Property.init(initial:then:)`

[api breaking]Make some operators to accept SignalProducerConvertible conforming types

---

CHANGELOG.md
Sources/Lifetime.swift
Tests/ReactiveSwiftTests/LifetimeSpec.swift

This hopefully makes attaching lifetime to producer chains more natural.
```swift
let (lifetime, token) = Lifetime.make()
let producer = SignalProducer.combineLatest(conditionA, conditionB, conditionC)
.filter { $0 && $1 && $2 }
// Before
producer.startWithCompleted { _ = token }
// After
producer.startWithCompleted(token.dispose)
```

Introduce `Lifetime.Token.dispose`.

---

ReactiveSwift.podspec

This sets the cocoapod dependency to match the current dependency set in Carthage.

updating Result dependency in ReactiveSwift.podspec to 4.0'

---

CHANGELOG.md
Cartfile.private
Cartfile.resolved
ReactiveSwift.xcodeproj/project.pbxproj
Sources/ValidatingProperty.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Xcode 10 support

---

CHANGELOG.md
ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift
Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

This operator is useful when we want to handle Result without to complete stream.
It has semantics similar to `dematerialize`.
And `dematerializeResults` which works in inverse is also added.
Use case:
```swift
// This stream doesn't complete even if an error sent.
viewModel.reactive.date.producer
.take(duringLifetimeOf: self)
.flatMap(.latest) { date in
repository.getPrograms(on: date)
.materializeResults()
}
.startWithValues { result in
switch result {
case .success(let programs)
print(programs)
case .failure(let error)
print(error)
}
```

Add materializeResults operator

---

Documentation/ReactivePrimitives.md

Clean up and clarify some language in ReactivePrimitives.md.

[Documentation] Clean up Reactive Primitives documentation

---

CHANGELOG.md
Sources/Scheduler.swift

This also fixes the deprecation error in Swift 5.

Implement the new hash method in Hashable

---

.travis.yml
Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift
Package@swift-4.2.swift
ReactiveSwift.xcodeproj/project.pbxproj

- https://github.com/Quick/Quick/releases/tag/v2.0.0
- https://github.com/Quick/Nimble/releases/tag/v8.0.0
This is required to build using Xcode 10.2. But we require Swift 4.2 at least now, so we must drop Swift 4.1 support.

Update Quick to 2.0.0 and Nimble to 8.0.0

---

CHANGELOG.md
ReactiveSwift.podspec
Sources/Info.plist
Tests/ReactiveSwiftTests/Info.plist

I'd like to release our changes for Xcode 10.2. Since we dropped Swift 4.1, this needs to be a breaking release.
I don't think we need to do a beta release for this, but I'm open to other opinions. 🙂
@ReactiveCocoa/reactiveswift

Bump the version to 5.0

---

CHANGELOG.md

As proposed in https://github.com/ReactiveCocoa/ReactiveSwift/pull/724

Add a short upgrade guide for 6.0.0

---

README.md
ReactiveSwift.playground/Pages/Property.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Sandbox.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/Signal.xcplaygroundpage/Contents.swift
ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift

Delete an unnecessary setup for playground

---

CHANGELOG.md
Sources/ResultExtensions.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/FlattenSpec.swift
Tests/ReactiveSwiftTests/ReactiveExtensionsSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Hi.
`public protocol ResultProtocol `, `public var value: Success?` & `public var error: Failure?` brings ambiguity for those who wrote their own extensions or use [antitypical/Result](https://github.com/antitypical/Result).
This PR attempts to fix this issue.

Fix Result extensions ambiguity

---

CHANGELOG.md
Sources/UnidirectionalBinding.swift
Tests/ReactiveSwiftTests/UnidirectionalBindingSpec.swift

~As the title says, I think it would be nice to make `Observer` conform to `BindingTargetProvider`.
Any thoughts on that?~
This PR adds the binding operator to `Signal.Observer`

Add binding operator to Signal.Observer

---

README.md

Update the badge image for the Swift version from 4.2 to 5.0.
Resolves #736

Update badge image on shield.io to Swift 5

---

CHANGELOG.md
Sources/FoundationExtensions.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Usually on my projects I do use more properties to determine state of some `Property`, e.g. `isLoading` property usually depends on more properties which later on ends like this
```
action1.isExecuting.or(action2.isExecuting)...or(actionX.isExecuting)
```
Then I end up with extensions which simplify such code and I think it might be useful for more people than just me.
This PR adds static function `and` and `or` to `SignalProducer`, `PropertyProtocol` with appropriate attributes which solves such case elegantly.

Add possibility to use `and` + `or` with collection of signals/properties

---

Documentation/APIContracts.md
Documentation/BasicOperators.md
Documentation/DebuggingTechniques.md
Documentation/FrameworkOverview.md
Documentation/ReactivePrimitives.md
Documentation/RxComparison.md

It seems like this was changed [in version 6.0.0](https://github.com/ReactiveCocoa/ReactiveSwift/blob/b772fa0b624926e6e2f21acbb79297736a05c585/CHANGELOG.md#600), and this updates the documentation to reflect that change. :)

Replace the `NoError` type with `Never` in documentation

---

ReactiveSwift.podspec

- ~[ ] Updated CHANGELOG.md.~
Refs:
- https://github.com/ReactiveCocoa/ReactiveSwift/pull/743#discussion_r321955557
- http://blog.cocoapods.org/CocoaPods-1.7.0-beta/#support-for-multiple-swift-versions

[podspec] Update cocoapods_version to `>= 1.7.0` to use `swift_versions` DSL

---

Sources/FoundationExtensions.swift

This fixes the following compiler warning:
```
Switch covers known cases, but 'DispatchTimeInterval' may have additional unknown values, possibly added in future versions.
```
Not 100% sure if `.infinity` and `.never` are the best values to return here, but I guess it's also unlikely we'll ever actually have new cases in the enum.

Add @unknown default to silence a warning

---

CHANGELOG.md
Sources/Action.swift
Sources/Event.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

I've renamed `filterMap` to `compactMap` so that it would be more in line with the Swift [compactMap](https://developer.apple.com/documentation/swift/sequence/2950916-compactmap) and the Combine [CompactMap Publisher](https://developer.apple.com/documentation/combine/publishers/compactmap).

Rename filterMap to compactMap

---

Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Instead, generate an array of pipes which can be fed to the transformation method
and then start all producers in a loop, connecting each to the corresponding pipe
This fixes #729 
I suspect that with significantly more effort one could refactor the Signal aggregate strategy to avoid creating the set of pipes by allowing for dynamic aggregation.
However, it may happen that eventually, such refactor will result in a comparable overhead down the line.

SignalProducer: avoid recursive start of a sequence of producers

---

Sources/Flatten.swift

Update `FlattenStrategy.throttle` docs.

---

CHANGELOG.md
Sources/Event.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Fixes issue #771. Thanks @andersio for the quick solution on this.
I also added tests that show the solution works. The tests were added at a commit before the change that fixed it so it's easy to verify that tests fail before the change but not after.

Fix debounce when started twice

---

CHANGELOG.md
Sources/Signal.swift

this becomes relevant, when joining 1000 signals and more
✅ Updated CHANGELOG.md.

Increased performance of joining signals by a factor of around 5

---

.travis.yml
ReactiveSwift.xcodeproj/xcshareddata/xcschemes/ReactiveSwift-macOS.xcscheme
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Swift 5.2 in Xcode 11.4 seems to be preempting deinitialization of objects to be as earliest as possible, when optimization mode is on (`-O -Owholemodule`). That breaks a few test cases, which have the deinitialization reordered before the pre-deinit assertions. These are fixed by applying `withExtendedLifetime` as appropriate.

Move CI to Xcode 11.4 and update the tests.

---

CHANGELOG.md
Sources/Event.swift
Sources/Property.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Joining empty list of producers fix

---

CHANGELOG.md
Sources/Property.swift
Tests/ReactiveSwiftTests/PropertySpec.swift

Relevant context: https://github.com/ReactiveCocoa/ReactiveSwift/pull/762#issuecomment-632793302
These types would not go away even if we continue to evolve #762, and marking them as property wrapper is a reasonable transitional solution to improve QoL until that happens.
`Property` and `MutableProperty` can be used as property wrappers without controversy IMO — they will continue to be reference type containers, so there is no surprise awaiting new RAS users.

Mark Property and MutableProperty as property wrappers.

---

Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Merged old PRs that contain reference to `NoError`, which broke `master`.

Fix merge artifacts NoError -> Never

---

README.md

* Introduce an official curated "extended modules" list. 
* Declare that there is no plan for ABI/module stability guarantees yet.
* Remove references to the old UI examples, as I am not sure if these are what we want to promote anymore in the today's field.

Restructure readme to incorporate a list of "extended modules".

---

CHANGELOG.md
Sources/Atomic.swift

It seems `EDEADLK` could be returned by `pthread_mutex_trylock` in earlier OS versions, according to #747. Let's add it to the known happy path.

Be more tolerate with error code returned by `pthread_mutex_trylock`.

---

ReactiveSwift.podspec

We have adopted `@propertyWrapper` which requires Swift 5.1+.

Stop declaring Swift 5.0 support.

---

Sources/EventLogger.swift

Replaced manually enumerated `allEvents` to `allCases` from CaseIterable.
- ~~[ ] Updated CHANGELOG.md~~.

replaced allEvents by allCases

---

CHANGELOG.md
Package.resolved
Package.swift

When `ReactiveSwift` is imported as a `swift package` using Xcode 12, it generates following warning `deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.` This PR fixes the warning by bumping the min. deployment target to iOS 9 when importing this dependency as a swift packages
I've also updated `Quick` and `Nimble` dependencies to their latest versions. The `ReactiveCocoa` counterpart PR is here https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3712.

bump package target to iOS 9 and update testing packages

---

Documentation/RxCheatsheet.md

Is the `Combine` caption in the Operators table correct?
I think the correct caption is `ReactiveSwift`.

Fix caption `Combine` to `ReactiveSwift`

---

CHANGELOG.md
Sources/Optional.swift

Hi, this is just a very small contribution regarding the `OptionalProtocol` and adds the `ExpressibleByNilLiteral` constraint to it. It is already implemented by `Optional<Wrapped>` and requires no further change. This makes it possible to initialise a value of type `OptionalProtocol` with `nil` instead of having to write `.init(reconstructing: nil)`.
There also was a small typo in the documentation of the `associatedType` which I fixed as well.
```swift
extension Property where Value: OptionalProtocol {
func mapNil() -> Property<Value> {
// now possible to write
return Property(value: nil)
// instead of
return Property(value: .init(reconstructing: nil))
}
}
```
Extending `OptionalProtocol` with the implementation of `ExpressibleByNilLiteral` is not possible due to a language constraint: …

Add ExpressibleByNilLiteral constraint to OptionalProtocol

---

CHANGELOG.md
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalLifetimeSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

`SignalProducer.lift` might leak intermediate signals, if the upstream has been terminated, way before a downstream interruption is raised.

Fix a `SignalProducer.lift` issue which may leak intermediate signals. 

---

CHANGELOG.md
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Hi 👋 
This is my first contribution, albeit a small one.
What I'd like to add is variadic argument support for static intializers of `Signal`s, `SignalProducer`s and `Properties` where `Value == Boolean`.
So, similar to how we write `SignalProducer.combineLatest(producer1, producer2)` we could write `SignalProducer.any(producer1, producer2)` - right now we have to do `SignalProducer.any([producer1, producer2])` which seems unnecessarily verbose.
I have also change a few test cases to leverage this new feature

Add variadic sugar for boolean static methods.

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Event.swift
Sources/Observers/AttemptMap.swift
Sources/Observers/Dematerialize.swift
Sources/Observers/DematerializeResults.swift
Sources/Observers/MapError.swift
Sources/Observers/Materialize.swift
Sources/Observers/MaterializeAsResult.swift
Sources/Observers/Observer.swift

The new abstraction was introduced in #799.
Migrated operators in this PR include:
MapError, Materialize, MaterializeAsResult, AttemptMap, Dematerialize, DematerializeResults 

Migrate six operators to the new abstraction.

---

CHANGELOG.md
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

Adds the `interval` operator with functionality similar to that of the operator with the same name in [ReactiveX](http://reactivex.io/RxJava/javadoc/rx/Observable.html#interval-long-java.util.concurrent.TimeUnit-rx.Scheduler-).
Allows specifying any `Sequence`, including infinite sequences such as `0...` (which is the sequence used if none is provided, to mimic the ReactiveX behaviour).
This can be useful, for example, to make a "typewriter" effect of characters appearing on the screen at regularly spaced intervals.

Adds the `interval` operator.

---

Sources/Disposable.swift
Sources/Property.swift
Sources/Scheduler.swift
Sources/Signal.swift

This is only to remove five compiler warnings.
I was updating my iOS app to be able to run on Xcode 12.5 (beta) and noticed that Apple is now flagging the use of class inherited protocols as deprecated in favor of inheriting from AnyObject. In my iOS app, we flag warnings as errors so now our app won't compile. I wanted to be able to pitch in and help modernize the code so I went ahead and fixed this deprecation here.
After a little bit of research, I came across this forum Swift.org [post](https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507/4) which seems to point to the discussion where this deprecation discussion started.

Fixed a deprecation warning where some protocols were inheriting from class instead of AnyObject per Xcode's suggestion

---

CHANGELOG.md
Sources/SignalProducer.swift

Make the code compatible with Swift 5.1 and 5.2 again. Resolves #822
Prior to Swift 5.3 a `where` clause could not be used in a function that is itself not generic, even if used within a generic context. The only way to do this is to use a specific extension and put the `where` clause in the extension.

Remove requirement for Swift 5.3

---

CHANGELOG.md
Sources/Lifetime.swift

Just a small typo fix in the documentation for `Token` in `Lifetime.swift`.

Fix typo ("conjuncion" --> "conjunction")

---

CHANGELOG.md
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift

The `currentDate` in `TestScheduler` could already be advanced by
`DispatchTimeInterval`. In unit tests the developer might want to
reuse an existing constant, which often is a `Double`/`TimeInterval`.
This PR adds a second method with exactly the same signature as the
existing one; only the type of the argument is different.

Make advance by TimeInterval in TestScheduler possible

---

.gitignore
CHANGELOG.md
Sources/Atomic.swift
Sources/Property.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

1. `Signal` now offers an unserialized variant and a reentrant variant for advanced users. (#797)
These new primitives would be adopted by ReactiveCocoa UIKit bindings to improve interoperability with RAC Loop, to tackle some legitimate recursive delivery scenarios (e.g. around first responder management), and also to reduce fine-grained locking across ReactiveSwift and ReactiveCocoa.
Note that the default behavior of `Signal` has not been changed — event serialization remains the default behavior. `MutableProperty` is also not gonna be reentrant, because there is no sane reentrancy model that supports access to the current value and multicasting [while being compliant to the Property contract](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/APIContracts.md#events- …

Unserialized and Reentrant `Signal`s

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Event.swift
Sources/Observers/Delay.swift
Sources/Observers/LazyMap.swift
Sources/Observers/ObserveOn.swift
Sources/Observers/UnaryAsyncOperator.swift

The new abstraction was introduced in #799.
Migrated operators in this PR include: ObserveOn, LazyMap, Delay.
A new base class `UnaryAsyncOperator` has been introduced to unify the delicate termination handling in all unary async operators, that was once replicated across all individual implementations. The logic has also be strengthened to guarantee that double termination is impossible, by tracking a binary active/terminated state per operator instance using atomics.

Migrate ObserveOn, LazyMap and Delay to the new abstraction, while unifying delicate logic in these operators.

---

ReactiveSwift.xcodeproj/project.pbxproj
Sources/Event.swift
Sources/Observers/CollectEvery.swift
Sources/Observers/Debounce.swift
Sources/Observers/Throttle.swift
Sources/Observers/UnaryAsyncOperator.swift

The new abstraction was introduced in #799.
Migrated operators in this PR include: Debounce, Throttle, CollectEvery.
Blocked by #815 since these operators depend on the new base class `UnaryAsyncOperator` in #815.
Throttle was partly rewritten around its own `DebounceState`, dropping its reliance on `ThrottleState` (which has slightly different semantics, and sharing the state rep is more a hack).

Migrate Debounce, Throttle and CollectEvery to the new abstraction.

---

Sources/Event.swift

This `enum` isn't expected to change. It's important to mark it as `@frozen`
so that clients don't get warnings whem compiling with `BUILD_LIBRARY_FOR_DISTRIBUTION`,
which might be required in a future version of Carthage supporting Catalyst.
(See https://github.com/Carthage/Carthage/pull/3235).

Signal.Event: changed to `@frozen`

---

CHANGELOG.md
ReactiveSwift.xcodeproj/project.pbxproj
Sources/Event.swift
Sources/Observers/TakeUntil.swift
Sources/Signal.swift
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerLiftingSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

Forward any values until `shouldContinue` returns `false`, at which point the returned signal forwards the last value and then it completes.
This is equivalent to `take(while:)`, except it also forwards the last value that failed the check.
I was going to add this to my own project as an extension, but a consequence of #799 is that it's not "impossible" (not as trivial as before) to add these operators, since things like `flatMapEvent` and `Event.Transformation` aren't `public`.
So I wanted this PR to serve as a conversation. I think this operator can be useful, but also it might be worth exploring how we can make it easier to declare outside of ReactiveSwift, maybe exposing some of these new types?

Add take(until:) operator

---

ReactiveSwift.playground/contents.xcplayground

Before|After
-|-
Checked with Xcode 13.1.0

Fix "No such module 'ReactiveSwift'" in Playground pages by enabling "buildActiveScheme"

---

ReactiveSwift.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift

This fixes the `'value' is inaccessible due to 'internal' protection level` of the SignalProducer playground page
```
error: SignalProducer.xcplaygroundpage:138:17: error: 'value' is inaccessible due to 'internal' protection level
print(result.value)
^~~~~
```
Caused by #733

Fix "'value' is inaccessible due to 'internal' protection level" in SignalProducer playground

---

CHANGELOG.md
Sources/SignalProducer.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift

This fixes an issue where state is shared between different `start` invocations of the same producer.
```swift
let p = someProducer.retry(upTo: 1, interval: interval, on:scheduler)
p.start(...) // This consumes retries for the purpose of delaying errors
...
p.start(...) // Retries for the purpose of delaying errors can be negative here, resulting in the last error not being sent immediately.
```

Fix shared state in retry

---

CHANGELOG.md
Sources/UnidirectionalBinding.swift

This fixes the `<~` operator returning optional values even though it should be able to just return non optional ones.

UnidirectionalBinding should return non optionals

---

.github/workflows/test.yml
CHANGELOG.md
Sources/SignalProducer.swift

- Test against Xcode 14.1 and 13.4.1
- Use setup-swift action to install specific swift versions (replaces swiftenv script)
- Test against Swift 5.2 and 5.7

Refactor Github Actions to cover more swift versions

---

CHANGELOG.md
Sources/SignalProducer.swift

Adds [primary associated types](https://github.com/apple/swift-evolution/blob/main/proposals/0346-light-weight-same-type-syntax.md) to `SignalProducerConvertible` and `SignalProducerProtocol`

Add primary associated types to SignalProducerConvertible & SignalProducerProtocol

---

CHANGELOG.md
ReactiveSwift.xcodeproj/project.pbxproj
Sources/FoundationExtensions.swift
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/DateSchedulerAsyncTestCase.swift
Tests/ReactiveSwiftTests/TestSchedulerAsyncTestCase.swift

Credits to @pointfreeco for the work done in:
https://github.com/pointfreeco/combine-schedulers
- Add new `async` APIs to `DateScheduler` to enable waiting for them in asynchronous contexts:
+ `sleep(for:leeway:) async`
+ `sleep(until:leeway:) async`
+ `timer(interval:leeway:) async`
- Add new `async` variants `TestScheduler`'s `advance` and `run` APIs, to enable waiting for them in asynchronous contexts:
+ `advance()` async`
+ `advance(by:) async` (`DispatchTimeInterval` and `TimeInterval`)
+ `advance(to:) async`
+ `run() async`
- Refactor `TestScheduler.advance(to:)`'s loop condition to be based on `_currentDate` instead of `scheduledActions.count` to be consistent with the new `async` variant.
- I've not added any tests for now, as I would like to know if the solution/approach is …

Add `async` helpers to Schedulers

---

Sources/Atomic.swift
Sources/Scheduler.swift

The changes made in #859 went a little too far in removing the Swift version check, without which building fails on Xcode 13.x, so I added it back.

Guard use of OSAllocatedUnfairLock with a Swift 5.7 version check to allow building on Xcode 13.x

---

CHANGELOG.md
Documentation/RxCheatsheet.md
Package.swift
README.md
ReactiveSwift.podspec
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/ActionSpec.swift
Tests/ReactiveSwiftTests/PropertySpec.swift
Tests/ReactiveSwiftTests/QueueScheduler+Factory.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift
Tests/ReactiveSwiftTests/SignalProducerSpec.swift
Tests/ReactiveSwiftTests/SignalSpec.swift

This updates all deployment target minimums to the values supported by Xcode 14.
It removes spurious warnings of the form:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99.
```

Bump Minimums OSes to suppress Xcode 14 warnings

---

CHANGELOG.md
ReactiveSwift.podspec
ReactiveSwift.xcodeproj/project.pbxproj

This explicitly declares that ReactiveSwift only uses extension safe APIs (and/or APIs in an extension-safe way).
The code was already extension safe; this just forward declares it and enforces it at compile time.
If I can enforce this here, then I can enforce it in [Workflow](https://github.com/square/Workflow-swift) which is heavily dependent on this library.
Without this explicit conformance, it is not straightforward to write CI validation that these libraries remain extension safe.
There is zero harm in explicit conformance. Non-extension applications can call into extension-safe libraries without any restrictions.

Explicit extension safety flag

---

.github/workflows/master.yml
CHANGELOG.md

Apparently GH action's push event filters accept glob patterns and *not* regexes :facepalm:
Source:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
That means that the existing tag filter string being a regex wasn't working properly and as such wasn't triggering the expected builds on tag push.
To address this, the `on.push.tags` were updated to have separate entries for normal vs `rc` tags, and also tweaked the tag-only jobs' filters to rely on `github.ref_type` instead of inspecting `github.ref`.

Fix CI release git tag push trigger

---

.github/workflows/test.yml
CHANGELOG.md
Sources/Bag.swift

Given that tokens are always added to the end of the array and have a monotonically increasing value, this list is always sorted, so we can use a binary search to improve performance if this list gets large.

Use binary search for removing elements from Bag

---

ReactiveSwift-UIExamples.playground/Pages/ValidatingProperty.xcplaygroundpage/Contents.swift

As https://github.com/ReactiveCocoa/ReactiveSwift/pull/702 has been merged a looong time ago, the mention of `Result` should be omitted.

Remove Result mention from Playground

---

CHANGELOG.md
Sources/Disposable.swift

This adds an extension on `ScopedDisposable` where the inner is a `SerialDisposable`. This allows you to easily update the `inner` of the `SerialDisposable` wrapped in the `ScopedDisposable`.
Example:
```
let scopedDisposable = ScopedDisposable(SerialDisposable())
scopedDisposable.inner = someDisposble
```

Add extension to ScopedDisposable for SerialDisposable

---

CHANGELOG.md
Sources/Scheduler.swift
Tests/ReactiveSwiftTests/SchedulerSpec.swift

after doing a bit of research on how libdispatch's 'quality of service' (QoS) propagation logic works, i noticed that the default behavior of `QueueScheduler` is slightly different than what one would get if just using a `DispatchQueue`. i'm not sure if this was intentional, but in practice the consequence is that if you do something like this:
```swift
// assume we're on the main dispatch queue, i.e. QoS is 'user interactive'
let scheduler = QueueScheduler()
scheduler.schedule {
// do something...
}
```
you end up with the inferred QoS of the scheduled block being set to 'default' QoS, whereas it would be 'user initiated' if using a vanilla `DispatchQueue`. this patch changes the default `qos` parameter from `.default` to `.unspecified` to match `DispatchQueue`'s default behavior. this …

Use unspecified QoS in QueueScheduler when QoS is unspecified

---

CHANGELOG.md
Sources/Property.swift
Sources/UnidirectionalBinding.swift

Including the following protocols 
- PropertyProtocol
- MutablePropertyProtocol
- ComposableMutablePropertyProtocol
- BindingSource
- BindingTargetProvider

Add primary associated types to property and binding protocols
